export const CONSTANT = "CONSTANT";

export const UPDATE_CART = "UPDATE_CART";
export const UPDATE_COUNT = "UPDATE_COUNT";

//auth actionTypes
export const REQUEST_SIGNUP_START = "REQUEST_SIGNUP_START";
export const REQUEST_SIGNUP_SUCCESS = "REQUEST_SIGNUP_SUCCESS";
export const REQUEST_SIGNUP_FAIL = "REQUEST_SIGNUP_FAIL";

export const REQUEST_USERLOGIN_START = "REQUEST_USERLOGIN_START";
export const REQUEST_USERLOGIN_SUCCESS = "REQUEST_USERLOGIN_SUCCESS";
export const REQUEST_USERLOGIN_FAIL = "REQUEST_USERLOGIN_FAIL";

export const SIGNOUT_START = "SIGNOUT";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_FAIL = "SIGNOUT_FAIL";
