export const CONSTANT = "CONSTANT";

export const UPDATE_CART = "UPDATE_CART";
export const UPDATE_COUNT = "UPDATE_COUNT";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";

export const SET_DELIVERY_DETAILS = "SET_DELIVERY-DETAILS";

export const CLEAR_ALL_STATE_DATA = "CLEAR_ALL_STATE_DATA";

//auth actionTypes
export const REQUEST_SIGNUP_START = "REQUEST_SIGNUP_START";
export const REQUEST_SIGNUP_SUCCESS = "REQUEST_SIGNUP_SUCCESS";
export const REQUEST_SIGNUP_FAIL = "REQUEST_SIGNUP_FAIL";

export const REQUEST_LOGIN_START = "REQUEST_LOGIN_START";
export const REQUEST_LOGIN_SUCCESS = "REQUEST_LOGIN_SUCCESS";
export const REQUEST_LOGIN_FAIL = "REQUEST_LOGIN_FAIL";

export const SIGNOUT = "SIGNOUT";

export const CHECK_AUTH_STATE = "CHECK_AUTH_STATE";

export const GET_USER_DATA_START = "GET_USER_DATA_START";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_FAIL = "GET_USER_DATA_FAIL";
